-- AlterTable
ALTER TABLE "app_settings" ADD COLUMN "ftpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "app_settings" ADD COLUMN "ftpUsername" TEXT;
ALTER TABLE "app_settings" ADD COLUMN "ftpPasswordCiphertext" TEXT;
ALTER TABLE "app_settings" ADD COLUMN "ftpListenPort" INTEGER NOT NULL DEFAULT 2121;
ALTER TABLE "app_settings" ADD COLUMN "ftpPasvMinPort" INTEGER NOT NULL DEFAULT 50100;
ALTER TABLE "app_settings" ADD COLUMN "ftpPasvMaxPort" INTEGER NOT NULL DEFAULT 50109;
ALTER TABLE "app_settings" ADD COLUMN "ftpPasvAddress" TEXT;

-- CreateTable
CREATE TABLE "cdr_records" (
    "id" TEXT NOT NULL,
    "cdrAt" TIMESTAMP(3),
    "cdr_id" TEXT NOT NULL,
    "cdr_date" TEXT NOT NULL,
    "in_ani" TEXT NOT NULL,
    "in_dnis" TEXT NOT NULL,
    "out_ani" TEXT NOT NULL,
    "out_dnis" TEXT NOT NULL,
    "bill_ani" TEXT NOT NULL,
    "bill_dnis" TEXT NOT NULL,
    "sig_node_name" TEXT NOT NULL,
    "src_gatekeeper_address" TEXT NOT NULL,
    "remote_src_sig_address" TEXT NOT NULL,
    "remote_dst_sig_address" TEXT NOT NULL,
    "remote_src_media_address" TEXT NOT NULL,
    "remote_dst_media_address" TEXT NOT NULL,
    "local_src_sig_address" TEXT NOT NULL,
    "local_dst_sig_address" TEXT NOT NULL,
    "local_src_media_address" TEXT NOT NULL,
    "local_dst_media_address" TEXT NOT NULL,
    "in_leg_proto" TEXT NOT NULL,
    "out_leg_proto" TEXT NOT NULL,
    "conf_id" TEXT NOT NULL,
    "in_leg_call_id" TEXT NOT NULL,
    "out_leg_call_id" TEXT NOT NULL,
    "src_user" TEXT NOT NULL,
    "dst_user" TEXT NOT NULL,
    "radius_user" TEXT NOT NULL,
    "src_name" TEXT NOT NULL,
    "dst_name" TEXT NOT NULL,
    "dp_name" TEXT NOT NULL,
    "elapsed_time" TEXT NOT NULL,
    "setup_time" TEXT NOT NULL,
    "connect_time" TEXT NOT NULL,
    "disconnect_time" TEXT NOT NULL,
    "in_leg_codecs" TEXT NOT NULL,
    "out_leg_codecs" TEXT NOT NULL,
    "src_faststart_present" TEXT NOT NULL,
    "dst_faststart_present" TEXT NOT NULL,
    "src_tunneling_present" TEXT NOT NULL,
    "dst_tunneling_present" TEXT NOT NULL,
    "proxy_mode" TEXT NOT NULL,
    "lar_fault_reason" TEXT NOT NULL,
    "route_retries" TEXT NOT NULL,
    "scd" TEXT NOT NULL,
    "pdd" TEXT NOT NULL,
    "media_group" TEXT NOT NULL,
    "src_media_bytes_in" TEXT NOT NULL,
    "src_media_bytes_out" TEXT NOT NULL,
    "dst_media_bytes_in" TEXT NOT NULL,
    "dst_media_bytes_out" TEXT NOT NULL,
    "src_media_packets" TEXT NOT NULL,
    "dst_media_packets" TEXT NOT NULL,
    "src_media_packets_late" TEXT NOT NULL,
    "dst_media_packets_late" TEXT NOT NULL,
    "src_media_packets_lost" TEXT NOT NULL,
    "dst_media_packets_lost" TEXT NOT NULL,
    "src_min_jitter_size" TEXT NOT NULL,
    "src_max_jitter_size" TEXT NOT NULL,
    "dst_min_jitter_size" TEXT NOT NULL,
    "dst_max_jitter_size" TEXT NOT NULL,
    "last_cdr" TEXT NOT NULL,
    "in_cpc" TEXT NOT NULL,
    "out_cpc" TEXT NOT NULL,
    "in_zone" TEXT NOT NULL,
    "out_zone" TEXT NOT NULL,
    "disconnect_initiator" TEXT NOT NULL,
    "in_ani_type_of_number" TEXT NOT NULL,
    "in_dnis_type_of_number" TEXT NOT NULL,
    "out_ani_type_of_number" TEXT NOT NULL,
    "out_dnis_type_of_number" TEXT NOT NULL,
    "src_in_leg_conf_id" TEXT NOT NULL,
    "src_in_leg_call_id" TEXT NOT NULL,
    "src_out_leg_call_id" TEXT NOT NULL,
    "in_orig_dnis" TEXT NOT NULL,
    "out_orig_dnis" TEXT NOT NULL,
    "record_type" TEXT NOT NULL,
    "extradata" TEXT NOT NULL,
    "term_elapsed_time" TEXT NOT NULL,
    "term_setup_time" TEXT NOT NULL,
    "term_connect_time" TEXT NOT NULL,
    "term_disconnect_time" TEXT NOT NULL,
    "term_scd" TEXT NOT NULL,
    "term_pdd" TEXT NOT NULL,
    "external_router" TEXT NOT NULL,
    "radius_group" TEXT NOT NULL,
    "in_ani_screening" TEXT NOT NULL,
    "in_ani_presentation" TEXT NOT NULL,
    "out_ani_screening" TEXT NOT NULL,
    "out_ani_presentation" TEXT NOT NULL,
    "outgoing_pulses" TEXT NOT NULL,
    "incoming_pulses" TEXT NOT NULL,
    "in_lrn" TEXT NOT NULL,
    "retrieved_lrn" TEXT NOT NULL,
    "lrn" TEXT NOT NULL,
    "ext_lrn" TEXT NOT NULL,
    "out_lrn" TEXT NOT NULL,
    "lnp_server" TEXT NOT NULL,
    "in_leg_transport_proto" TEXT NOT NULL,
    "out_leg_transport_proto" TEXT NOT NULL,
    "sip_routing_group" TEXT NOT NULL,
    "looping_cycles" TEXT NOT NULL,
    "auth_dnis" TEXT NOT NULL,
    "ext_ani" TEXT NOT NULL,
    "ext_dnis" TEXT NOT NULL,
    "ext_sig_address" TEXT NOT NULL,
    "in_partner_id" TEXT NOT NULL,
    "out_partner_id" TEXT NOT NULL,
    "disconnect_code_string" TEXT NOT NULL,
    "disconnect_code_success" TEXT NOT NULL,
    "src_disconnect_codes_string" TEXT NOT NULL,
    "dst_disconnect_codes_string" TEXT NOT NULL,
    "in_orig_dnis_type_of_number" TEXT NOT NULL,
    "out_orig_dnis_type_of_number" TEXT NOT NULL,
    "in_encryption" TEXT NOT NULL,
    "out_encryption" TEXT NOT NULL,
    "ext_ani_type_of_number" TEXT NOT NULL,
    "ext_dnis_type_of_number" TEXT NOT NULL,
    "ext_orig_dnis_type_of_number" TEXT NOT NULL,
    "src_disconnect_codes" TEXT NOT NULL,
    "dst_disconnect_codes" TEXT NOT NULL,
    "disconnect_code" TEXT NOT NULL,
    "sourceFilename" TEXT NOT NULL,
    "importedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastJobRunId" TEXT,

    CONSTRAINT "cdr_records_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "cdr_records_cdr_id_key" ON "cdr_records"("cdr_id");
CREATE INDEX "cdr_records_cdrAt_idx" ON "cdr_records"("cdrAt" DESC);
CREATE INDEX "cdr_records_in_ani_idx" ON "cdr_records"("in_ani");
CREATE INDEX "cdr_records_in_dnis_idx" ON "cdr_records"("in_dnis");
CREATE INDEX "cdr_records_out_ani_idx" ON "cdr_records"("out_ani");
CREATE INDEX "cdr_records_out_dnis_idx" ON "cdr_records"("out_dnis");
CREATE INDEX "cdr_records_src_name_idx" ON "cdr_records"("src_name");
CREATE INDEX "cdr_records_dst_name_idx" ON "cdr_records"("dst_name");
CREATE INDEX "cdr_records_disconnect_code_string_idx" ON "cdr_records"("disconnect_code_string");

ALTER TABLE "cdr_records" ADD CONSTRAINT "cdr_records_lastJobRunId_fkey" FOREIGN KEY ("lastJobRunId") REFERENCES "job_runs"("id") ON DELETE SET NULL ON UPDATE CASCADE;
